import { Character } from 'rickmortyapi';

export const MOCK_DATA: Character[] = [
  {
    created: 'created',
    episode: [''],
    gender: 'Female',
    id: 1,
    image: 'https://via.placeholder.com/300',
    location: { name: '', url: '' },
    status: 'Alive',
    species: '',
    type: '',
    origin: { name: '', url: '' },
    name: 'Morty Smith',
    url: '',
  },
  {
    created: 'created',
    episode: [''],
    gender: 'Female',
    id: 2,
    image: 'https://via.placeholder.com/300',
    location: { name: '', url: '' },
    status: 'Alive',
    species: '',
    type: '',
    origin: { name: '', url: '' },
    name: 'Morty Smith',
    url: '',
  },
  {
    created: 'created',
    episode: [''],
    gender: 'Female',
    id: 3,
    image: 'https://via.placeholder.com/300',
    location: { name: '', url: '' },
    status: 'Alive',
    species: '',
    type: '',
    origin: { name: '', url: '' },
    name: 'Morty Smith',
    url: '',
  },
  {
    created: 'created',
    episode: [''],
    gender: 'Female',
    id: 4,
    image: 'https://via.placeholder.com/300',
    location: { name: '', url: '' },
    status: 'Alive',
    species: '',
    type: '',
    origin: { name: '', url: '' },
    name: 'Morty Smith',
    url: '',
  },
];
